name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: it-mbti/package-lock.json

    # Navigate to project directory and install dependencies
    - name: Install dependencies
      run: npm ci
      working-directory: ./it-mbti

    # Build the project if build script exists
    - name: Build the project
      run: npm run build --if-present
      working-directory: ./it-mbti

    # Run tests
    - name: Run tests
      run: npm test
      working-directory: ./it-mbti
